{% set name = "kinparse" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 943296e80302d23743e4045b42254fb6edbd0d1da5340bc4844a0844a45d6bf8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kinparse = kinparse.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - future >=0.15.0
    - pyparsing >=2.1.1

test:
  imports:
    - kinparse

about:
  home: https://github.com/xesscorp/kinparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a parser for KiCad schematic netlist files that are output by EESCHEMA

extra:
  recipe-maintainers:
    - hmaarrfk
